# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        MyShop\AdminBundle\Entity\User: plaintext
        MyShop\DefaultBundle\Entity\Customer: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: MyShop\AdminBundle\Entity\User
                property: username

        customer_db_provider:
            entity:
                class: MyShop\DefaultBundle\Entity\Customer
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /admin/*
            provider: db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

        shop:
            provider: customer_db_provider
            anonymous: ~
            form_login:
                login_path: login_customer
                check_path: login_customer
            logout:
                path:   logout_customer
                target: /

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/basket, roles: ROLE_CUSTOMER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
