login:
    path: /login
    defaults: { _controller: MyShopAdminBundle:Login:login }

my_shop_admin.index:
    path:   /
    defaults: { _controller: MyShopAdminBundle:Default:index }

my_shop_admin.product_add:
    path:   /product/add
    defaults: { _controller: MyShopAdminBundle:Product:add }

my_shop_admin.product_list:
    path:   /product/list/{page}-{countPerPage}
    defaults: { _controller: MyShopAdminBundle:Product:list, page: 1, countPerPage: 5 }
    requirements:
        page: \d+
        countPerPage: \d+

my_shop_admin.product_list_by_category:
    path:   /category/{id_category}/product/list
    defaults: { _controller: MyShopAdminBundle:Product:listByCategory }
    requirements:
        id_category: \d+

my_shop.admin.product_delete:
    path:   /product/{id}/delete
    defaults: { _controller: MyShopAdminBundle:Product:delete }
    requirements:
        id: \d+

my_shop_admin.product_edit:
    path:   /product/{id}/edit
    defaults: { _controller: MyShopAdminBundle:Product:edit }
    requirements:
        id: \d+

my_shop_admin.product_photo_add:
    path:   /product/{idProduct}/photo/add
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:add }
    requirements:
        idProduct: \d+

my_shop_admin.product_photo_list:
    path:   /product/{idProduct}/photos
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:list }
    requirements:
        idProduct: \d+

my_shop_admin.product_photo_send_mail:
    path:   /product/photo/{id}/sendmail
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:sendToMail }
    requirements:
        id: \d+

my_shop_admin.category_add:
    path:   /category/add/{idParent}
    defaults: { _controller: MyShopAdminBundle:Category:add, idParent:null }

my_shop_admin.category_list:
    path:   /category/list/{idParentCategory}
    defaults: { _controller: MyShopAdminBundle:Category:list, idParentCategory:null }
    requirements:
        idParentCategory: \d+

my_shop_admin.category_tree:
    path:   /category/tree
    defaults: { _controller: MyShopAdminBundle:Category:tree }

my_shop_admin.user_add:
    path: /user/add
    defaults: { _controller: MyShopAdminBundle:User:add }

my_shop_admin.load_demo_users:
    path: /loaddemo/users
    defaults: { _controller: MyShopAdminBundle:Default:loadUsers }

my_shop_admin.products_import_csv:
    path:   /products/import/csv
    defaults: { _controller: MyShopAdminBundle:ProductsLoader:importProducts }

my_shop_admin.products_export_csv:
    path:   /products/export/csv
    defaults: { _controller: MyShopAdminBundle:ProductsLoader:exportProducts }

my_shop_admin.testfile:
    path:   /testfile
    defaults: { _controller: MyShopAdminBundle:Product:testfile }

my_shop_admin.page_list:
    path:   /pages
    defaults: { _controller: MyShopAdminBundle:Page:index }

my_shop_admin.page_add:
    path:   /page/add
    defaults: { _controller: MyShopAdminBundle:Page:add }

my_shop_admin.page_edit:
    path:   /page/{id}/edit
    defaults: { _controller: MyShopAdminBundle:Page:edit }
    requirements:
        id: \d+

my_shop_admin.upload_image:
    path:   /upload_image
    defaults: { _controller: MyShopAdminBundle:Default:uploadImage }

my_shop_admin.test_api:
    path: /testapi
    defaults: { _controller: MyShopAdminBundle:TestApi:index }